severity: error


rules:

  mixins-before-declarations: 0
  no-warn: 0
  property-sort-order: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  class-name-format: 0
  nesting-depth:
    - 1
    -
      max-depth: 4
      ignore_parent_selectors: true




linters:

  BorderZero:
    enabled: true
    convention: zero

  BemDepth:
    enabled: true

  DeclarationOrder:
    enabled: false

  ExtendDirective:
    enabled: true

  LeadingZero:
    enabled: false

  NameFormat:
    enabled: true

  PrivateNamingConvention:
    enabled: true
    prefix: _

  PropertySortOrder:
    enabled: false

  QualifyingElement:
    enabled: false

  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM
    class_convention: ^(?!js-).*
    class_convention_explanation: should not be written in the form js-*

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false

  StringQuotes:
    enabled: true
    style: double_quotes

  NestingDepth:
    enabled: true
    max_depth: 3
    ignore_parent_selectors: true


